//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.DeploymentToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visus.DeploymentToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear state variable.
        /// </summary>
        internal static string ClearState {
            get {
                return ResourceManager.GetString("ClearState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files.
        /// </summary>
        internal static string CopyFiles {
            get {
                return ResourceManager.GetString("CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create directory.
        /// </summary>
        internal static string CreateDirectory {
            get {
                return ResourceManager.GetString("CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current user.
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay execution.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount deployment share.
        /// </summary>
        internal static string MountDeploymentShare {
            get {
                return ResourceManager.GetString("MountDeploymentShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount network drive.
        /// </summary>
        internal static string MountNetworkShare {
            get {
                return ResourceManager.GetString("MountNetworkShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist task sequence state.
        /// </summary>
        internal static string PersistState {
            get {
                return ResourceManager.GetString("PersistState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt for credential.
        /// </summary>
        internal static string PromptCredential {
            get {
                return ResourceManager.GetString("PromptCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to deployment share.
        /// </summary>
        internal static string PromptDeploymentShare {
            get {
                return ResourceManager.GetString("PromptDeploymentShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string PromptDomain {
            get {
                return ResourceManager.GetString("PromptDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment mount point.
        /// </summary>
        internal static string PromptMountPoint {
            get {
                return ResourceManager.GetString("PromptMountPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PromptPassword {
            get {
                return ResourceManager.GetString("PromptPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string PromptUser {
            get {
                return ResourceManager.GetString("PromptUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy state information.
        /// </summary>
        internal static string ReinterpretState {
            get {
                return ResourceManager.GetString("ReinterpretState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring the deployment state from &quot;{0}&quot;..
        /// </summary>
        internal static string RestoringState {
            get {
                return ResourceManager.GetString("RestoringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run deployment agent.
        /// </summary>
        internal static string RunAgent {
            get {
                return ResourceManager.GetString("RunAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run command.
        /// </summary>
        internal static string RunCommand {
            get {
                return ResourceManager.GetString("RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set an environment variable.
        /// </summary>
        internal static string SetEnvironmentVariable {
            get {
                return ResourceManager.GetString("SetEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set keyboard locale.
        /// </summary>
        internal static string SetKeyboardLocale {
            get {
                return ResourceManager.GetString("SetKeyboardLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the working directory state.
        /// </summary>
        internal static string SetWorkingDirectory {
            get {
                return ResourceManager.GetString("SetWorkingDirectory", resourceCulture);
            }
        }
    }
}
