//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.DeploymentToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visus.DeploymentToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding task {0} to the list of tasks for phase {1}..
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} finished with exit code {1}..
        /// </summary>
        internal static string CommandExecuted {
            get {
                return ResourceManager.GetString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command {0}..
        /// </summary>
        internal static string CommandExecuting {
            get {
                return ResourceManager.GetString("CommandExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying all files from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string CopyFiles {
            get {
                return ResourceManager.GetString("CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying recursively from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string CopyRecursively {
            get {
                return ResourceManager.GetString("CopyRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring that the destination folder &quot;{0}&quot; exists..
        /// </summary>
        internal static string CreatingDestinationFolder {
            get {
                return ResourceManager.GetString("CreatingDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a task list for phase {0}..
        /// </summary>
        internal static string CreatingTaskListForPhase {
            get {
                return ResourceManager.GetString("CreatingTaskListForPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current user.
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting task {0} at position {2}  in phase {1}..
        /// </summary>
        internal static string InsertTask {
            get {
                return ResourceManager.GetString("InsertTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping &quot;{0}&quot; to &quot;{1}&quot; as {2}..
        /// </summary>
        internal static string MountingShare {
            get {
                return ResourceManager.GetString("MountingShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount network drive.
        /// </summary>
        internal static string MountNetworkShare {
            get {
                return ResourceManager.GetString("MountNetworkShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring the deployment state from &quot;{0}&quot;..
        /// </summary>
        internal static string RestoringState {
            get {
                return ResourceManager.GetString("RestoringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run command.
        /// </summary>
        internal static string RunCommand {
            get {
                return ResourceManager.GetString("RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persisting the deployment state to &quot;{0}&quot;..
        /// </summary>
        internal static string SavingState {
            get {
                return ResourceManager.GetString("SavingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} finished in phase {1}..
        /// </summary>
        internal static string TaskFinished {
            get {
                return ResourceManager.GetString("TaskFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} is starting in phase {1}..
        /// </summary>
        internal static string TaskStarting {
            get {
                return ResourceManager.GetString("TaskStarting", resourceCulture);
            }
        }
    }
}
