//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.DeploymentToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visus.DeploymentToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding task {0} to the list of tasks for phase {1}..
        /// </summary>
        internal static string AddingTaskToPhase {
            get {
                return ResourceManager.GetString("AddingTaskToPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} finished with exit code {1}..
        /// </summary>
        internal static string CommandExecuted {
            get {
                return ResourceManager.GetString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command {0}..
        /// </summary>
        internal static string CommandExecuting {
            get {
                return ResourceManager.GetString("CommandExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a task list for phase {0}..
        /// </summary>
        internal static string CreatingTaskListForPhase {
            get {
                return ResourceManager.GetString("CreatingTaskListForPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying unattend file &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string DismApplyUnattend {
            get {
                return ResourceManager.GetString("DismApplyUnattend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing changes..
        /// </summary>
        internal static string DismCommit {
            get {
                return ResourceManager.GetString("DismCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising DISM with &quot;{0}&quot; as log file and &quot;{1}&quot; as scratch directory..
        /// </summary>
        internal static string DismInitialise {
            get {
                return ResourceManager.GetString("DismInitialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening offline servicing session for &quot;{0}&quot;..
        /// </summary>
        internal static string DismOpenOffline {
            get {
                return ResourceManager.GetString("DismOpenOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down DISM..
        /// </summary>
        internal static string DismShutdown {
            get {
                return ResourceManager.GetString("DismShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting task {0} at position {2}  in phase {1}..
        /// </summary>
        internal static string InsertingTaskToPhase {
            get {
                return ResourceManager.GetString("InsertingTaskToPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition and format disk.
        /// </summary>
        internal static string PartitionFormatDisk {
            get {
                return ResourceManager.GetString("PartitionFormatDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run command.
        /// </summary>
        internal static string RunCommand {
            get {
                return ResourceManager.GetString("RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select installation disk.
        /// </summary>
        internal static string SelectInstallDisk {
            get {
                return ResourceManager.GetString("SelectInstallDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} finished in phase {1}..
        /// </summary>
        internal static string TaskFinished {
            get {
                return ResourceManager.GetString("TaskFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task sequence {0}.
        /// </summary>
        internal static string TaskSequenceName {
            get {
                return ResourceManager.GetString("TaskSequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} is starting in phase {1}..
        /// </summary>
        internal static string TaskStarting {
            get {
                return ResourceManager.GetString("TaskStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the Virtual Disk Service to become ready..
        /// </summary>
        internal static string WaitingVds {
            get {
                return ResourceManager.GetString("WaitingVds", resourceCulture);
            }
        }
    }
}
