//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.DeploymentToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visus.DeploymentToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a cab or msu package.
        /// </summary>
        internal static string AddPackage {
            get {
                return ResourceManager.GetString("AddPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a cab or msu package to Windows PE.
        /// </summary>
        internal static string AddWindowsPePackage {
            get {
                return ResourceManager.GetString("AddWindowsPePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply WIM image.
        /// </summary>
        internal static string ApplyImage {
            get {
                return ResourceManager.GetString("ApplyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply unattend.xml.
        /// </summary>
        internal static string ApplyUnattend {
            get {
                return ResourceManager.GetString("ApplyUnattend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for administrative permissions.
        /// </summary>
        internal static string CheckElevation {
            get {
                return ResourceManager.GetString("CheckElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the boostrapper.
        /// </summary>
        internal static string CopyBootstrapper {
            get {
                return ResourceManager.GetString("CopyBootstrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy unattend.xml.
        /// </summary>
        internal static string CopyUnattend {
            get {
                return ResourceManager.GetString("CopyUnattend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Windows Pre-installed Environment.
        /// </summary>
        internal static string CopyWindowsPe {
            get {
                return ResourceManager.GetString("CopyWindowsPe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Windows PE ISO.
        /// </summary>
        internal static string CreateIso {
            get {
                return ResourceManager.GetString("CreateIso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customise unattend.xml.
        /// </summary>
        internal static string CustomiseUnattend {
            get {
                return ResourceManager.GetString("CustomiseUnattend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable a Windows feature.
        /// </summary>
        internal static string EnableFeature {
            get {
                return ResourceManager.GetString("EnableFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject drivers.
        /// </summary>
        internal static string InjectDrivers {
            get {
                return ResourceManager.GetString("InjectDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Windows PE.
        /// </summary>
        internal static string InstallWindowsPe {
            get {
                return ResourceManager.GetString("InstallWindowsPe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A debugging task sequence which will deploy the Windows PE boot image to the local disk..
        /// </summary>
        internal static string InstallWindowsPeDescription {
            get {
                return ResourceManager.GetString("InstallWindowsPeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join domain or workgroup.
        /// </summary>
        internal static string JoinDomain {
            get {
                return ResourceManager.GetString("JoinDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen.
        /// </summary>
        internal static string LockScreen {
            get {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount a WIM image.
        /// </summary>
        internal static string MountWim {
            get {
                return ResourceManager.GetString("MountWim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition and format disk.
        /// </summary>
        internal static string PartitionFormatDisk {
            get {
                return ResourceManager.GetString("PartitionFormatDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage a deployment share.
        /// </summary>
        internal static string PrepareDeploymentShare {
            get {
                return ResourceManager.GetString("PrepareDeploymentShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task sequence.
        /// </summary>
        internal static string PromptInstallationImage {
            get {
                return ResourceManager.GetString("PromptInstallationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation image.
        /// </summary>
        internal static string PromptTaskSequence {
            get {
                return ResourceManager.GetString("PromptTaskSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot machine.
        /// </summary>
        internal static string RebootMachine {
            get {
                return ResourceManager.GetString("RebootMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A task sequence requires the machine to be restarted..
        /// </summary>
        internal static string RebootMessage {
            get {
                return ResourceManager.GetString("RebootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify a registry value.
        /// </summary>
        internal static string RegistryValue {
            get {
                return ResourceManager.GetString("RegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove provisioned appx packages.
        /// </summary>
        internal static string RemoveAppxPackage {
            get {
                return ResourceManager.GetString("RemoveAppxPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure boot sector.
        /// </summary>
        internal static string RestoreBootConfiguration {
            get {
                return ResourceManager.GetString("RestoreBootConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the installation bootstrapper copying the required files from the network and starts the agent..
        /// </summary>
        internal static string RunDeimosBootstrapper {
            get {
                return ResourceManager.GetString("RunDeimosBootstrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select WIM image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select task sequence.
        /// </summary>
        internal static string SelectInstallationSequence {
            get {
                return ResourceManager.GetString("SelectInstallationSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select installation disk.
        /// </summary>
        internal static string SelectInstallDisk {
            get {
                return ResourceManager.GetString("SelectInstallDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a folder.
        /// </summary>
        internal static string ShareFolder {
            get {
                return ResourceManager.GetString("ShareFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task sequence {0}.
        /// </summary>
        internal static string TaskSequenceName {
            get {
                return ResourceManager.GetString("TaskSequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmount a WIM image.
        /// </summary>
        internal static string UnmountWim {
            get {
                return ResourceManager.GetString("UnmountWim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete shared resource.
        /// </summary>
        internal static string Unshare {
            get {
                return ResourceManager.GetString("Unshare", resourceCulture);
            }
        }
    }
}
